### ISSUE TITLE
fix: mlflow issues when running with `n_jobs`

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#797]
We have a few problems here, which I think stem from`optuna` using `multithreading` for `n_jobs`. 

I think this leads to one mlflow instance that is shared by all the threads. Some of the symptoms that lead me to think that:

* A run can get oof_4 metrics, without having metrics from other folds. I think this indicates cross-run logging contamination, e.g. [this run](http://exrhel0371.it.rm.dk:5050/#/experiments/283459040257106139/runs/f348d7a38b6746b88e671e4198be818b). 

* We get an MLFlow error 500 on some run initialisations. [Allegedly](https://github.com/mlflow/mlflow/issues/6169), this can be due to trying to log the same parameter again on a run. This could happen, for example, if there is cross-run logging contamination. 
<details>
  <summary>Stack trace of error 500</summary>
  
```bash
[W 2024-01-31 14:31:37,611] Trial 15 failed because of the following error: MlflowException("API request to http://exrhel0371.it.rm.dk:5050/api/2.0/mlflow/runs/log-batch failed with exception HTTPConnectionPool(host='exrhel0371.it.rm.dk',
port=5050): Max retries exceeded with url: /api/2.0/mlflow/runs/log-batch (Caused by ResponseError('too many 500 error responses'))")
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\urllib3\connectionpool.py", line 946, in urlopen
    return self.urlopen(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\urllib3\connectionpool.py", line 946, in urlopen
    return self.urlopen(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\urllib3\connectionpool.py", line 946, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\urllib3\connectionpool.py", line 936, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='exrhel0371.it.rm.dk', port=5050): Max retries exceeded with url: /api/2.0/mlflow/runs/log-batch (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\utils\rest_utils.py", line 107, in http_request
    return _get_http_response_with_retries(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\utils\request_utils.py", line 197, in _get_http_response_with_retries
    return session.request(method, url, allow_redirects=allow_redirects, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\requests\adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='exrhel0371.it.rm.dk', port=5050): Max retries exceeded with url: /api/2.0/mlflow/runs/log-batch (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\hyperparameter_suggester\optuna_hyperparameter_search.py", line 107, in <lambda>
    lambda trial: OptunaHyperParameterOptimization()._optuna_objective(
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\hyperparameter_suggester\optuna_hyperparameter_search.py", line 81, in _optuna_objective
    concrete_config_schema.logger.log_config(Config(concrete_config))
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\loggers\multi_logger.py", line 39, in log_config
    self._run_on_loggers(lambda logger: logger.log_config(config=config))
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\loggers\multi_logger.py", line 21, in _run_on_loggers
    func(logger)
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\loggers\multi_logger.py", line 39, in <lambda>
    self._run_on_loggers(lambda logger: logger.log_config(config=config))
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\loggers\mlflow_logger.py", line 89, in log_config
    mlflow.log_params(sanitise_dict_keys(flattened_config))
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\tracking\fluent.py", line 863, in log_params
    return MlflowClient().log_batch(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\tracking\client.py", line 1093, in log_batch
    return self._tracking_client.log_batch(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 444, in log_batch
    self.store.log_batch(
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\store\tracking\rest_store.py", line 323, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\store\tracking\rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\utils\rest_utils.py", line 218, in call_endpoint
    response = http_request(**call_kwargs)
  File "E:\ProgramData\Anaconda3\envs\psycop\lib\site-packages\mlflow\utils\rest_utils.py", line 129, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to http://exrhel0371.it.rm.dk:5050/api/2.0/mlflow/runs/log-batch failed with exception HTTPConnectionPool(host='exrhel0371.it.rm.dk', port=5050): Max retries exceeded with url: /api/2.0/mlflow
/runs/log-batch (Caused by ResponseError('too many 500 error responses'))
```

</details>

### Proposed solutions
Optuna [does not support](https://github.com/optuna/optuna/issues/4539) a joblib-based backend, but we can add our own wrapper around it. I'm implementing that currently.

**Comment by MartinBernstorff** [comment]
@HLasse Orientation here. Solution in [this commit](https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/795/commits/c56cce9754ecea95ea3e3d503522c4835e6c0f40).
